# Generated by Django 6.0.1 on 2026-01-21 12:14

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ING', 'Ingenierías'), ('BIO', 'Biomédicas'), ('SOC', 'Sociales')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('eje_tematico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('puntaje_final', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pagado_reporte', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacro.area')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('carrera', models.CharField(help_text='Ej: Ingeniería de Sistemas', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_especifico', models.CharField(help_text='Ej: Ecuaciones Diferenciales', max_length=200)),
                ('texto_pregunta', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Texto de la Pregunta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='preguntas/')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacro.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, help_text='Puede incluir código LaTeX entre $', max_length=500, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='alternativas/')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es la correcta?')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='simulacro.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_marcada', models.CharField(blank=True, max_length=1, null=True)),
                ('es_correcta', models.BooleanField(default=False)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='simulacro.intento')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacro.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='MatrizPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_pregunta', models.DecimalField(decimal_places=7, max_digits=10)),
                ('cantidad_preguntas', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacro.area')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacro.asignatura')),
            ],
            options={
                'unique_together': {('area', 'asignatura')},
            },
        ),
    ]
