# Generated by Django 6.0.1 on 2026-01-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrizpeso',
            name='peso_pregunta',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
