# Generated by Django 6.0.1 on 2026-02-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacro', '0002_alter_matrizpeso_peso_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(choices=[('ING', 'Ingenierías'), ('BIO', 'Biomédicas'), ('SOC', 'Sociales'), ('EXT', 'Extraordinario')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='matrizpeso',
            name='peso_pregunta',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
