# Generated by Django 6.0.1 on 2026-02-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacro', '0003_alter_area_nombre_alter_matrizpeso_peso_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='etiqueta',
            field=models.CharField(default='SIMULACRO_1', max_length=50),
        ),
        migrations.AlterField(
            model_name='respuestadetalle',
            name='opcion_marcada',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
