# Generated by Django 6.0.1 on 2026-02-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacro', '0004_pregunta_etiqueta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='reporte_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reportes_pdf/'),
        ),
    ]
