# Generated by Django 6.0.1 on 2026-07-06 15:11

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacro', '0005_intento_reporte_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='nivel_acceso',
            field=models.IntegerField(choices=[(0, 'Nivel 0: Gratis (Solo Nota Final)'), (1, 'Nivel 1: Diagnóstico S/ 10 (Semáforo + Reporte PDF)'), (2, 'Nivel 2: VIP S/ 25 (Todo + Solucionario PDF)')], default=0, verbose_name='Nivel de Desbloqueo'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='solucion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='soluciones/', verbose_name='Foto de resolución a mano (Opcional)'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='solucion_texto',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Explicación / Solucionario'),
        ),
    ]
