# Generated by Django 5.2.1 on 2026-08-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacro', '0007_alter_alternativa_id_alter_area_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilestudiante',
            name='examen_habilitado',
            field=models.BooleanField(default=False, verbose_name='Examen habilitado'),
        ),
    ]
