# Generated by Django 5.2.1 on 2026-08-08 16:32

import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacro', '0008_perfilestudiante_examen_habilitado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativas'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='asignatura',
            options={'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='intento',
            options={'verbose_name': 'Intento', 'verbose_name_plural': 'Intentos'},
        ),
        migrations.AlterModelOptions(
            name='matrizpeso',
            options={'verbose_name': 'Matriz de Peso', 'verbose_name_plural': 'Matriz de Pesos'},
        ),
        migrations.AlterModelOptions(
            name='perfilestudiante',
            options={'verbose_name': 'Perfil Estudiante', 'verbose_name_plural': 'Perfiles Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='respuestadetalle',
            options={'verbose_name': 'Respuesta Detalle', 'verbose_name_plural': 'Respuestas Detalle'},
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='email_verificado',
            field=models.BooleanField(default=False, verbose_name='Email verificado'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='es_correcta',
            field=models.BooleanField(default=False, verbose_name='Es la correcta?'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(blank=True, help_text='Puede incluir codigo LaTeX entre $', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(choices=[('ING', 'Ingenierias'), ('BIO', 'Biomedicas'), ('SOC', 'Sociales'), ('EXT', 'Extraordinario')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='intento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='intento',
            name='nivel_acceso',
            field=models.IntegerField(choices=[(0, 'Nivel 0: Gratis (Solo Nota Final)'), (1, 'Nivel 1: Diagnostico S/ 10 (Semaforo + Reporte PDF)'), (2, 'Nivel 2: VIP S/ 25 (Todo + Solucionario PDF)')], default=0, verbose_name='Nivel de Desbloqueo'),
        ),
        migrations.AlterField(
            model_name='matrizpeso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilestudiante',
            name='carrera',
            field=models.CharField(help_text='Ej: Ingenieria de Sistemas', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilestudiante',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='solucion_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='soluciones/', verbose_name='Foto de resolucion a mano (Opcional)'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='solucion_texto',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Explicacion / Solucionario'),
        ),
        migrations.AlterField(
            model_name='respuestadetalle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='intento',
            index=models.Index(fields=['estudiante', 'area', 'fecha_inicio'], name='simulacro_i_estudia_24b487_idx'),
        ),
        migrations.AddIndex(
            model_name='intento',
            index=models.Index(fields=['estudiante', '-fecha_inicio'], name='simulacro_i_estudia_bfbb97_idx'),
        ),
        migrations.AddIndex(
            model_name='intento',
            index=models.Index(fields=['-puntaje_final'], name='simulacro_i_puntaje_5a2f6d_idx'),
        ),
    ]
