# Generated by Django 5.2.1 on 2026-08-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacro', '0009_alter_alternativa_options_alter_area_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='en_curso',
            field=models.BooleanField(default=False, verbose_name='Examen en curso'),
        ),
        migrations.AddField(
            model_name='intento',
            name='preguntas_orden',
            field=models.JSONField(blank=True, null=True, verbose_name='Orden de preguntas'),
        ),
        migrations.AddField(
            model_name='perfilestudiante',
            name='puede_rendir',
            field=models.BooleanField(default=True, verbose_name='Puede rendir examen'),
        ),
    ]
