# Generated by Django 5.2.1 on 2026-08-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacro', '0010_intento_en_curso_intento_preguntas_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='segundos_activos',
            field=models.IntegerField(default=0, verbose_name='Segundos activos acumulados'),
        ),
    ]
